### ISSUE TITLE
[Bug Report] DatetimePicker组件在真机预览toolbar会同时出现在top和bottom

### ISSUE THREAD

**Issue by zengjinlong** [youzan/vant-weapp#5660]
### 重现链接

![WechatIMG415](https://github.com/youzan/vant-weapp/assets/30890269/83b7c6c4-e9f3-445e-93c5-194b1e380e45)
`<van-action-sheet show="{{ show }}">
  <van-datetime-picker
  type="year-month"
  bind:confirm="selectedDate"
  value="{{ currentDate }}"
/>
</van-action-sheet>`

### Vant Weapp 版本

1.11.1

### 描述一下你遇到的问题。

DatetimePicker组件在真机预览的时候会同时出现两个toolbar，上下各一个。

### 重现步骤

用ActionSheet组件包裹一个DatetimePicker组件，然后ActionSheet的show属性设置成true

### 设备/浏览器

微信小程序，调试基础库：3.2.3

**Comment by joker-wei-j** [comment]
我也遇到了相同的问题，请问一下，该怎么解决

**Comment by johnsonwong666** [comment]
https://developers.weixin.qq.com/s/NwHGjamA7bM4 这个小程序代码片段修改一下，修改成你的情况然后重新分享一下过来看一下

**Comment by fujialez** [comment]
使用van-popup包裹van-datetime-picker也出现这个bug

**Comment by johnsonwong666** [comment]
> 使用van-popup包裹van-datetime-picker也出现这个bug

可以提供一个复现代码片段过来看一下吗？

**Comment by fujialez** [comment]
[Uploading minicode-11.rar…]()

**Comment by fujialez** [comment]
> > 使用van-popup包裹van-datetime-picker也出现这个bug
> 
> 可以提供一个复现代码片段过来看一下吗？

bug复现连接https://github.com/fujialez/vantpicker

**Comment by fujialez** [comment]
问题复现https://github.com/fujialez/vantpicker&nbsp;


α&nbsp;β&nbsp;γ&nbsp;δ&nbsp;ε&nbsp;ζ&nbsp;η&nbsp;λ
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年12月19日(星期二) 下午5:42
收件人: ***@***.***&gt;; 
抄送: "α β γ δ ε ζ η ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [youzan/vant-weapp] [Bug Report] DatetimePicker组件在真机预览toolbar会同时出现在top和bottom (Issue #5660)





  
使用van-popup包裹van-datetime-picker也出现这个bug
  
可以提供一个复现代码片段过来看一下吗？

**Comment by joker-wei-j** [comment]
> > 使用van-popup包裹van-datetime-picker也出现这个bug
> 
> 可以提供一个复现代码片段过来看一下吗
是版本不一样么，我看了你给的代码片段里面的版本是1.11.1，官网下载下来的是1.11.2

**Comment by fujialez** [comment]
上周下载的是1.11.1,刚试了下 1.11.2也有这个问题&nbsp;


α&nbsp;β&nbsp;γ&nbsp;δ&nbsp;ε&nbsp;ζ&nbsp;η&nbsp;λ
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年12月20日(星期三) 上午10:19
收件人: ***@***.***&gt;; 
抄送: "α β γ δ ε ζ η ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [youzan/vant-weapp] [Bug Report] DatetimePicker组件在真机预览toolbar会同时出现在top和bottom (Issue #5660)





   
使用van-popup包裹van-datetime-picker也出现这个bug
  
可以提供一个复现代码片段过来看一下吗
 是版本不一样么，我看了你给的代码片段里面的版本是1.11.1，官网下载下来的是1.11.2

**Comment by joker-wei-j** [comment]
> 上周下载的是1.11.1,刚试了下 1.11.2也有这个问题&nbsp; α&nbsp;β&nbsp;γ&nbsp;δ&nbsp;ε&nbsp;ζ&nbsp;η&nbsp;λ ***@***.*** &nbsp;
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: ***@***.***&gt;; 发送时间: 2023年12月20日(星期三) 上午10:19 收件人: ***@***.***&gt;; 抄送: "α β γ δ ε ζ η ***@***.***&gt;; ***@***.***&gt;; 主题: Re: [youzan/vant-weapp] [Bug Report] DatetimePicker组件在真机预览toolbar会同时出现在top和bottom (Issue #5660) 使用van-popup包裹van-datetime-picker也出现这个bug 可以提供一个复现代码片段过来看一下吗 是版本不一样么，我看了你给的代码片段里面的版本是1.11.1，官网下载下来的是1.11.2 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: ***@***.***&gt;
刚才看了一下作者提供的代码片段里面是正常d的，版本也是1.11.1

**Comment by fujialez** [comment]
这边通过其他人下载提供的代码也是有这个bug

**Comment by fujialez** [comment]
已经找到问题,原因是在小程序创建项目使用基础模板的app.json中配置"componentFramework":&nbsp;"glass-easel"属性,会在真机上复现这个问题,基础库3.2.4,vantweapp1.11.1





α&nbsp;β&nbsp;γ&nbsp;δ&nbsp;ε&nbsp;ζ&nbsp;η&nbsp;λ
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "youzan/vant-weapp"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年12月20日(星期三) 上午10:40
***@***.***&gt;;
抄送:&nbsp;"α β γ δ ε ζ η ***@***.******@***.***&gt;;
主题:&nbsp;Re: [youzan/vant-weapp] [Bug Report] DatetimePicker组件在真机预览toolbar会同时出现在top和bottom (Issue #5660)





  
上周下载的是1.11.1,刚试了下 1.11.2也有这个问题&nbsp; α&nbsp;β&nbsp;γ&nbsp;δ&nbsp;ε&nbsp;ζ&nbsp;η&nbsp;λ @.*** &nbsp;
 …
 ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: @.&gt;; 发送时间: 2023年12月20日(星期三) 上午10:19 收件人: @.&gt;; 抄送: "α β γ δ ε ζ η @.&gt;; @.&gt;; 主题: Re: [youzan/vant-weapp] [Bug Report] DatetimePicker组件在真机预览toolbar会同时出现在top和bottom (Issue #5660) 使用van-popup包裹van-datetime-picker也出现这个bug 可以提供一个复现代码片段过来看一下吗 是版本不一样么，我看了你给的代码片段里面的版本是1.11.1，官网下载下来的是1.11.2 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: @.***&gt;
 刚才看了一下作者提供的代码片段里面是正常d的，版本也是1.11.1

**Comment by johnsonwong666** [comment]
按照 @fujialez 的方法
app.json 文件中删除 "componentFramework": "glass-easel" 试试

**Comment by joker-wei-j** [comment]
完美解决，谢谢

**Comment by johnsonwong666** [comment]
已反馈官方 官方在修复了
 https://github.com/wechat-miniprogram/glass-easel/issues/118
 
 临时解决
 app.json 文件中删除 "componentFramework": "glass-easel"
